routes/web.php
<?php
// phpinfo(); die;
Route::redirect('/', '/dashboard', 301);
Route::get('/dashboard', 'HomeController@index');

Route::get('/info', 'AutomationController@index');
Route::get('/addpermission/{permName}', 'AutomationController@addPermission');
Route::get('/fsdkduzelt', 'AutomationController@fsDakikaDuzelt');

Route::get('/fsLeague', 'AutomationController@fsLeague');
Route::get('/fsSeason', 'AutomationController@fsSeason');
Route::get('/fsGroup', 'AutomationController@fsGroup');
Route::get('/fsTeam', 'AutomationController@fsTeam');
Route::get('/fsPlayer', 'AutomationController@fsPlayer');
Route::get('/fsFixture', 'AutomationController@fsFixture');

Route::get('/fsGetMatchData', 'AutomationController@fsGetMatchData');
Route::get('/fsGetMatchActionData', 'AutomationController@fsGetMatchActionData');
Route::get('/fsGetMatchTeamData', 'AutomationController@fsGetMatchTeamData');

Route::get('/cropimage/{folder}/{image_url}', 'AjaxAppApiController@cropImages');

Auth::routes();

Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');

Route::get('/date/{param}', 'AutomationController@checkDate');

Route::get('/playerdegerguncelle/{player_id}', 'AutomationController@playerDegerGuncelle');
Route::get('/degeruygula/{offset}/{limit}', 'AutomationController@degerUygula');

Route::get('/sezonistatistikhesapla/{sezon_id}/{offset}/{limit}', 'AutomationController@sezonIstatistikHesapla');

Route::get('/videourldegistir/{offset}/{limit}', 'AutomationController@videoUrlDegistir');

//RoleProvince
Route::group(['prefix' => '/users'], function () {
	Route::get('/', 'UserController@index')->name('users');

	Route::get('/view/{id}', 'UserController@crud');
	Route::get('/add', 'UserController@crud');
	Route::get('/edit/{id}', 'UserController@crud');
	Route::get('/delete/{id}', 'UserController@crud');
	
	Route::post('/save', 'UserController@save');

	Route::get('/password/{id}', 'UserController@password');
	Route::post('/save_password', 'UserController@save_password');

	Route::get('/logo_delete/{id}', 'UserController@userPhotoDelete');
	Route::post('/logo_save', 'AjaxController@userPhotoSave');

});

//RoleProvince
Route::group(['prefix' => '/roles'], function () {
	Route::get('/', 'RoleController@index')->name('roles');

	Route::get('/view/{id}', 'RoleController@crud');
	Route::get('/add', 'RoleController@crud');
	Route::get('/edit/{id}', 'RoleController@crud');
	Route::get('/delete/{id}', 'RoleController@crud');
	
	Route::post('/save', 'RoleController@save');

	Route::get('/permission/{id}', 'RoleController@permission');
	Route::post('/permission_save', 'RoleController@permission_save');
});

//RoleProvince
Route::group(['prefix' => '/conferences'], function () {
	Route::get('/', 'ConferenceController@index')->name('conferences');

	Route::get('/view/{id}', 'ConferenceController@crud');
	Route::get('/add', 'ConferenceController@crud');
	Route::get('/edit/{id}', 'ConferenceController@crud');
	Route::get('/delete/{id}', 'ConferenceController@crud');
	
	Route::post('/save', 'ConferenceController@save');
});

//RoleProvince
Route::group(['prefix' => '/provinces'], function () {
	Route::get('/', 'ProvinceController@index')->name('provinces');

	Route::get('/view/{id}', 'ProvinceController@crud');
	Route::get('/add', 'ProvinceController@crud');
	Route::get('/edit/{id}', 'ProvinceController@crud');
	Route::get('/delete/{id}', 'ProvinceController@crud');
	
	Route::post('/save', 'ProvinceController@save');
});

//RoleProvince
Route::group(['prefix' => '/districts'], function () {
	Route::get('/', 'DistrictController@index')->name('districts');

	Route::get('/view/{id}', 'DistrictController@crud');
	Route::get('/add', 'DistrictController@crud');
	Route::get('/edit/{id}', 'DistrictController@crud');
	Route::get('/delete/{id}', 'DistrictController@crud');
	
	Route::post('/save', 'DistrictController@save');
});

//RoleProvince
Route::group(['prefix' => '/grounds'], function () {
	Route::get('/', 'GroundController@index')->name('grounds');

	Route::get('/view/{id}', 'GroundController@crud');
	Route::get('/add', 'GroundController@crud');
	Route::get('/edit/{id}', 'GroundController@crud');
	Route::get('/delete/{id}', 'GroundController@crud');
	Route::get('/hour/{id}', 'GroundController@ground_hour');
	
	Route::post('/save', 'GroundController@save');
});

Route::group(['prefix' => '/ground_properties'], function () {
	Route::get('/', 'GroundController@ground_properties')->name('ground_properties');

	Route::get('/view/{id}', 'GroundController@ground_properties_crud');
	Route::get('/add', 'GroundController@ground_properties_crud');
	Route::get('/edit/{id}', 'GroundController@ground_properties_crud');
	Route::get('/delete/{id}', 'GroundController@ground_properties_crud');
	
	Route::post('/save', 'GroundController@ground_properties_save');
});

//RoleProvince
Route::group(['prefix' => '/leagues'], function () {
	Route::get('/', 'LeagueController@index')->name('leagues');

	Route::get('/view/{id}', 'LeagueController@crud');
	Route::get('/add', 'LeagueController@crud');
	Route::get('/edit/{id}', 'LeagueController@crud');
	Route::get('/delete/{id}', 'LeagueController@crud');
	
	Route::post('/save', 'LeagueController@save');
});

Route::group(['prefix' => '/branches'], function () {
	Route::get('/', 'BranchController@index')->name('branches');

	Route::get('/view/{id}', 'BranchController@crud');
	Route::get('/add', 'BranchController@crud');
	Route::get('/edit/{id}', 'BranchController@crud');
	Route::get('/delete/{id}', 'BranchController@crud');
	
	Route::post('/save', 'BranchController@save');
});

Route::group(['prefix' => '/seasons'], function () {
	Route::get('/', 'SeasonController@index')->name('seasons');
	Route::get('/addbonus', 'SeasonController@addBonus');
	Route::post('/addbonus/save', 'SeasonController@addBonusSave');
});

Route::group(['prefix' => '/seasonsp'], function () {
	Route::get('/view/{id}', 'SeasonController@crudp');
	Route::get('/add', 'SeasonController@crudp');
	Route::get('/edit/{id}', 'SeasonController@crudp');
	Route::get('/delete/{id}', 'SeasonController@crudp');
	
	Route::post('/save', 'SeasonController@savep');
});

Route::group(['prefix' => '/seasonsf'], function () {
	Route::get('/view/{id}', 'SeasonController@crudf');
	Route::get('/add', 'SeasonController@crudf');
	Route::get('/edit/{id}', 'SeasonController@crudf');
	Route::get('/delete/{id}', 'SeasonController@crudf');
	
	Route::post('/save', 'SeasonController@savef');
});

Route::group(['prefix' => '/fixture_group'], function () {
	Route::get('/', 'SharedController@fixture_group')->name('fixture_group');

	Route::get('/view/{id}', 'SharedController@fixture_group_crud');
	Route::get('/add', 'SharedController@fixture_group_crud');
	Route::get('/edit/{id}', 'SharedController@fixture_group_crud');
	Route::get('/delete/{id}', 'SharedController@fixture_group_crud');
	
	Route::post('/save', 'SharedController@fixture_group_save');
	Route::get('/tree/{id}', 'SharedController@fixture_group_tree_crud');
	Route::post('/tree_save', 'SharedController@fixture_group_item_save');

	Route::get('/edit_order/{id}', 'SharedController@fixture_group_edit_order');
	Route::post('/save_order', 'SharedController@fixture_group_save_order');
});

Route::group(['prefix' => '/seasonse'], function () {
	Route::get('/view/{id}', 'SeasonController@crude');
	Route::get('/add', 'SeasonController@crude');
	Route::get('/edit/{id}', 'SeasonController@crude');
	Route::get('/delete/{id}', 'SeasonController@crude');
	
	Route::post('/save', 'SeasonController@savee');
});

Route::group(['prefix' => '/elimination_tree'], function () {
	Route::get('/', 'SharedController@elimination_tree')->name('elimination_tree');

	Route::get('/view/{id}', 'SharedController@elimination_tree_crud');
	Route::get('/add', 'SharedController@elimination_tree_crud');
	Route::get('/edit/{id}', 'SharedController@elimination_tree_crud');
	Route::get('/delete/{id}', 'SharedController@elimination_tree_crud');
	
	Route::post('/save', 'SharedController@elimination_tree_save');
	Route::get('/tree/{id}', 'SharedController@elimination_tree_tree_crud');
	Route::post('/tree_save', 'SharedController@elimination_tree_item_save');
});

Route::group(['prefix' => '/teams'], function () {
	Route::get('/', 'TeamController@index')->name('teams');

	Route::get('/view/{id}', 'TeamController@crud');
	Route::get('/add', 'TeamController@crud');
	Route::get('/edit/{id}', 'TeamController@crud');
	Route::get('/delete/{id}', 'TeamController@crud');
	
	Route::post('/save', 'TeamController@save');

	Route::get('/setCaptain/{id}/{pid}', 'TeamController@setCaptain');
	Route::get('/releasePlayer/{id}/{pid}', 'TeamController@releasePlayer');
	Route::get('/setPlayOff/{id}/{tsid}', 'TeamController@setPlayOff');
	Route::get('/setSquadLocked/{id}/{tsid}', 'TeamController@setSquadLocked');

	Route::post('/request_termination', 'TeamController@requestTermination');

	Route::get('/addinsideplayer/{id}', 'TeamController@addinsideplayer');
	Route::get('/addinsideplayer_save/{id}/{pid}', 'TeamController@addinsideplayer_save');

	Route::post('/addpoint', 'TeamController@addPoint');

	Route::get('/logo_delete/{id}', 'TeamController@teamLogoDelete');
	Route::get('/cover_delete/{id}', 'TeamController@teamCoverDelete');

	Route::post('/logo_save', 'AjaxController@teamLogoSave');
	Route::post('/cover_save', 'AjaxController@teamCoverSave');

});

Route::group(['prefix' => '/matches'], function () {
	Route::get('/', 'MatchController@index')->name('matches');

	Route::get('/view/{id}', 'MatchController@crud');
	Route::get('/add', 'MatchController@crud');
	Route::get('/edit/{id}', 'MatchController@crud');
	Route::get('/delete/{id}', 'MatchController@crud');

	Route::post('/save', 'MatchController@save');
});

Route::group(['prefix' => '/match_video'], function () {
	Route::post('/save', 'MatchController@match_video_save');
});

Route::group(['prefix' => '/match_player'], function () {
	Route::post('/save', 'MatchController@match_player_save');

app/Match.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Match extends Model
{
    protected $table = 'matches';
    protected $dateFormat = 'Y-m-d H:i:sO';
    public $timestamps = false;

    //public.matches.matches_coordinator_id_427875e1_fk_coordinators_id
    public function coordinator()
    {
        return $this->hasOne('App\Coordinator', 'id', 'coordinator_id');
    }

    //public.matches.matches_ground_id_91bba733_fk_grounds_id
    public function ground()
    {
        return $this->hasOne('App\Ground', 'id', 'ground_id');
    }

    //public.matches.matches_referee_id_4baa2316_fk_referees_id
    public function referee()
    {
        return $this->hasOne('App\Referee', 'id', 'referee_id');
    }

    //public.matches.matches_season_id_1c71f317_fk_seasons_id
    public function season()
    {
        return $this->belongsTo('App\Season', 'season_id', 'id');
    }

    //public.matches.matches_team1_id_7d18cbe0_fk_teams_id
    public function team1()
    {
        return $this->hasOne('App\Team', 'id', 'team1_id');
    }

    //public.matches.matches_team2_id_a6be4f57_fk_teams_id
    public function team2()
    {
        return $this->hasOne('App\Team', 'id', 'team2_id');
    }

    //public.eliminationtree_items.eliminationtree_items_match_id_059193c8_fk_matches_id
    public function eliminationtree_items()
    {
        return $this->hasOne('App\EliminationTreeItem', 'match_id', 'id');
    }
    


    //public.match_actions.match_actions_match_id_eb025b14_fk_matches_id
    public function match_action()
    {
        return $this->hasMany('App\MatchAction', 'match_id', 'id');
    }

    public function match_action_order_minute()
    {
        return $this->hasMany('App\MatchAction', 'match_id', 'id')->orderBy('minute', 'asc');
    }

    //public.match_image.match_image_match_id_f77ca2f0_fk_matches_id
    public function match_image()
    {
        return $this->hasMany('App\MatchImage', 'match_id', 'id');
    }

    //public.match_panorama.match_panorama_match_id_c7e8b252_fk_matches_id
    public function match_panorama()
    {
        return $this->hasMany('App\MatchPanorama', 'match_id', 'id');
    }

    //public.match_player.match_player_match_id_36a2729e_fk_matches_id
    public function match_player()
    {
        return $this->hasMany('App\MatchPlayer', 'match_id', 'id');
    }

    public function match_player_is_not_guest()
    {
        return $this->hasMany('App\MatchPlayer', 'match_id', 'id')->where('player_id', '!=', null);
    }

    public function match_player_is_guest()
    {
        return $this->hasMany('App\MatchPlayer', 'match_id', 'id')->where('player_id', null);
    }

    //public.match_video.match_video_match_id_47d9c0bb_fk_matches_id
    public function match_video()
    {
        return $this->hasOne('App\MatchVideo', 'match_id', 'id');
    }

    //public.penalties.panorama_penal_match_id_3a1b4f65_fk_matches_id

    //public.press_conferences.press_conferences_match_id_4ea38742_fk_matches_id
    public function match_press()
    {
        return $this->hasOne('App\PressConferences', 'match_id', 'id');
    }

    //public.reservations.reservations_match_id_ae01fb70_fk_matches_id
    public function reservation()
    {
        return $this->belongsTo('App\Reservation', 'id', 'match_id');
    }

    /*
    //***************
    //Get Date Format
    public function getCreatedAtAttribute($date)
    {
        return Carbon::parse($date)->format('Y-m-d H:i:sO');
    }

    public function getUpdatedAtAttribute($date)
    {
        return Carbon::parse($date)->format('Y-m-d H:i:sO');
    }

    //***************
    //Set Date Format
    public function setCreatedAtAttribute($date)
    {
        return Carbon::parse($date)->format('Y-m-d H:i:sO');
    }

    public function setUpdatedAtAttribute($date)
    {
        return Carbon::parse($date)->format('Y-m-d H:i:sO');
    }
    */
    
}

resources/views/tabs/match_action.blade.php
@php
   // dump($model_data->completed);
@endphp
<!--begin: Datatable-->
<table class="table table-separate table-head-custom table-hover tab-table" id="kt_datatable_match_actions">
    <thead>
        <tr>
            <th>ID</th>
            <th>{{ __('words.video_source') }}</th>
            <th>{{ __('words.video_embed_code') }}</th>
            <th>{{ __('words.team') }}</th>
            <th>{{ __('words.player') }}</th>
            <th>{{ __('words.action_type') }}</th>
            <th>{{ __('words.minute') }}</th>
            <th>{{ __('words.action') }}</th>
        </tr>
    </thead>
    <tbody>
        
   		@if(!empty(data_get($value_tabs, 'relationship')))

            @foreach ($model_data[data_get($value_tabs, 'relationship')] as $key_rel => $value_rel)
                <tr role="row">
                    <td>{{ $value_rel->id }}</td>  <!-- ID -->
                    <td>{{ $value_rel->embed_source }}</td>  <!-- {{ __('words.video_source') }} -->
                    <td>{{ $value_rel->embed_code }}</td>  <!-- {{ __('words.video_embed_code') }} -->
                    <td>{{ $value_rel->match_team->name }}</td>  <!-- Team -->
                    <td>
                    	@if(!empty($value_rel->match_player_id))
                    		@if(empty($value_rel->match_player->player_id))
                    			{{ $value_rel->match_player->guest_name }}
                    		@else
                    			{{ $value_rel->match_player->player->user->first_name.' '.$value_rel->match_player->player->user->last_name }}
                    		@endif
                    	@endif
                    </td>  <!-- Oyuncu -->
                    <td>{{ $value_rel->type }}</td>  <!-- {{ __('words.action_type') }} -->
                    <td>{{ $value_rel->minute }}</td>  <!-- Dakika -->
                    <td style="width: 110px;">
                        @if(!$model_data->completed && Request::segment(2) != 'delete')
                            <a href="#" id="{{$loop->index}}" class="btn btn-sm btn-clean btn-icon btn-hover-success match_action_edit_button" title="{{ __('words.edit_action') }}" role="button" data-toggle="tooltip" data-html="true" data-content="">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a href="#" class="btn btn-sm btn-clean btn-icon btn-hover-danger" role="button" data-toggle="popvstt" data-html="true" 

                            title="{{ __('words.delete_action') }}" 

                            data-content="
                                <p>
                                    ({{ $value_rel->match_team->name }})
                                    @if(!empty($value_rel->match_player_id))
                                        @if(empty($value_rel->match_player->player_id))
                                            {{ $value_rel->match_player->guest_name }}
                                        @else
                                            {{ $value_rel->match_player->player->user->first_name.' '.$value_rel->match_player->player->user->last_name }}
                                        @endif
                                    @endif
                                </p>
                                <p>
                                    Bu aksiyonu kaldırmak istiyor musunuz?
                                </p>
                                <a href='{{ url('match_action/delete/'.$model_data->id.'/'.$value_rel->id) }}' class='btn btn-sm btn-light-success font-weight-bold mr-2' title='{{ __('words.approve') }}'>{{ __('words.approve') }}</a>
                                <a href='#' class='btn btn-sm btn-light-danger font-weight-bold mr-2' title='{{ __('words.cancel') }}'>{{ __('words.cancel') }}</a>
                            ">
                                <i class="fas fa-times"></i>
                            </a>
                        @endif
                    </td>
                </tr>
            @endforeach

        @endif
        
    </tbody>
</table>
<!--end: Datatable-->

resources/views/tabs/match_heatmap.blade.php
<div class="form-group row">
	<label class="col-form-label col-lg-3 col-sm-12 text-lg-right"> {{ __('words.heatmap') }} </label>
	<div class="col-lg-6 col-sm-12">
		<div class="card card-custom overlay" style="width: 200px; margin: auto;">
		    <div class="card-body p-0">
		        <div class="overlay-wrapper" id="imgHeatmapPhoto">
		          <img src="{{ env('MEDIA_END').$model_data->heatmap }}" alt="" class="rounded" style="width: 200px; height: auto;" />
		        </div>
		        <div class="overlay-layer align-items-start justify-content-end pt-5 pr-5">
		            <a href="{{ url('users/logo_delete/'.$model_data->id) }}" class="btn btn-clean btn-icon" title="{{ __('words.delete_photo') }}" ><i class="fas fa-trash-alt"></i></a>
		        </div>
		    </div>
		</div>
	</div>
	<div class="col-lg-3 col-sm-12">
		<div class="dropzone dropzone-default dropzone-primary" id="kt_dropzone_heatmapphoto">
			<div class="dropzone-msg dz-message needsclick">
				<h3 class="dropzone-msg-title">{{ __('words.drag_and_drop_heatmap_photo_here_or_click_to_upload') }}</h3>
				<span class="dropzone-msg-desc">{{ __('words.you_can_only_upload_1_file') }}</span>
			</div>
		</div>
	</div>
</div>

resources/views/tabs/match_image.blade.php
<div class="form-group row">
	<label class="col-form-label col-lg-3 col-sm-12 text-lg-right"> </label>
	<div class="col-lg-12 col-sm-12">
		<div class="dropzone dropzone-default dropzone-primary" id="kt_dropzone">
			<div class="dropzone-msg dz-message needsclick">
				<h3 class="dropzone-msg-title">{{ __('words.drag_and_drop_files_here_or_click_to_upload') }}</h3>
				<span class="dropzone-msg-desc">{{ __('words.upload_10_files') }}</span>
			</div>
		</div>
	</div>
</div>

<form class='form' method='POST' action='{{ url('match_image/desc_save') }}'>
    {{ csrf_field() }}
    <input type='hidden' name='match_id' value='{{ $model_data->id }}'>
	<div class="row" id="imgMatchImages">
		@foreach ($model_data->match_image as $image)
			<div class="col-lg-4 col-sm-12">
				<div class="card card-custom overlay">
				    <div class="card-body p-0">
				        <div class="overlay-wrapper">
				          <img src="{{ env('MEDIA_END').$image->image }}" alt="" class="w-100 rounded"/>
				        </div>
				        <div class="overlay-layer align-items-start justify-content-end pt-5 pr-5">
				            <a href="{{ url('match_image/delete/'.$model_data->id.'/'.$image->id) }}" class="btn btn-clean btn-icon" title="{{ __('words.delete_photo') }}" ><i class="fas fa-trash-alt"></i></a>
				        </div>
				    </div>
				</div>
				<div class="form-group row" style="margin-top: 0.75rem;">
				    <div class="col-lg-12">
				        <input class="form-control" type="text" name="match_image[{{ $image->id }}]" placeholder="{{ __('words.photo_description') }}" max="160" value="{{ $image->description }}">
				    </div>
				</div>
			</div>
		@endforeach
	</div>


	<div class="row" style="padding: 2rem 0 0 0; border-top: 1px solid #EBEDF3;">
		<div class="col-lg-3"></div>
		<div class="col-lg-6">
			<button type="submit" class="btn btn-success mr-2">{{ __('words.save') }}</button>
			<button type="button" class="btn btn-secondary" onclick="history.back()">{{ __('words.cancel') }}</button>
		</div>
		<div class="col-lg-3 text-right"></div>
	</div>
</form>

resources/views/tabs/match_panorama.blade.php
@php
	//dump($model_data[data_get($value_tabs, 'relationship')]);
@endphp
<!--begin: Datatable-->
<table class="table table-separate table-head-custom table-hover tab-table" id="kt_datatable_match_panoramas">
    <thead>
        <tr>
            <th>ID</th>
            <th>{{ __('words.panorama') }}</th>
            <th>{{ __('words.player') }}</th>
            <th>{{ __('words.video_source') }}</th>
            <th>{{ __('words.video_embed_code') }}</th>
            <th>{{ __('words.action') }}</th>
        </tr>
    </thead>
    <tbody>
        
   		@if(!empty(data_get($value_tabs, 'relationship')))

   			@foreach ($model_data[data_get($value_tabs, 'relationship')] as $key_rel => $value_rel)
                <tr role="row">
                    <td>{{ $value_rel->id }}</td>  <!-- ID -->
                    <td>{{ $value_rel->panorama_type->name }}</td>  
                    <td>
                    	@if(!empty($value_rel->match_player_id))
                    		({{ $value_rel->match_player_panorama->team->name }})
                    		@if(empty($value_rel->match_player_panorama->player_id))
                    			{{ $value_rel->match_player_panorama->guest_name }}
                    		@else
                    			{{ $value_rel->match_player_panorama->player->user->first_name.' '.$value_rel->match_player_panorama->player->user->last_name }}
                    		@endif
                    	@endif
                    </td>  
                    <td>{{ $value_rel->embed_source }}</td>
                    <td>{{ $value_rel->embed_code }}</td>
                    <td style="width: 110px;">
                        @if(Request::segment(2) != 'delete')
                            <a href="#" id="{{$loop->index}}" class="btn btn-sm btn-clean btn-icon btn-hover-success match_panorama_edit_button" title="{{ __('words.edit_panorama') }}" role="button" data-toggle="tooltip" data-html="true" data-content="">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a href="#" class="btn btn-sm btn-clean btn-icon btn-hover-danger" role="button" data-toggle="popvstt" data-html="true" 

                            title="{{ __('words.delete_panorama') }}" 

                            data-content="
                                <p>
                                    ({{ $value_rel->match_player_panorama->team->name }})
                                    @if(!empty($value_rel->match_player_id))
                                        @if(empty($value_rel->match_player_panorama->player_id))
                                            {{ $value_rel->match_player_panorama->guest_name }}
                                        @else
                                            {{ $value_rel->match_player_panorama->player->user->first_name.' '.$value_rel->match_player_panorama->player->user->last_name }}
                                        @endif
                                    @endif
                                </p>
                                <p>
                                    Bu aksiyonu kaldırmak istiyor musunuz?
                                </p>
                                <a href='{{ url('match_panorama/delete/'.$model_data->id.'/'.$value_rel->id) }}' class='btn btn-sm btn-light-success font-weight-bold mr-2' title='{{ __('words.approve') }}'>{{ __('words.approve') }}</a>
                                <a href='#' class='btn btn-sm btn-light-danger font-weight-bold mr-2' title='{{ __('words.cancel') }}'>{{ __('words.cancel') }}</a>
                            ">
                                <i class="fas fa-times"></i>
                            </a>
                        @endif
                    </td>
                </tr>
            @endforeach

        @endif
        
    </tbody>
</table>
<!--end: Datatable-->

resources/views/tabs/reservation_offer.blade.php
<!--begin: Datatable-->
<table class="table table-separate table-head-custom table-hover tab-table" id="kt_datatable_reservation_offer">
    <thead>
        <tr>
            <th>ID</th>
            <th>{{ __('words.team') }}</th>
            <th>{{ __('words.status') }}</th>
            <th>{{ __('words.order_date') }}</th>
            <th>{{ __('words.action') }}</th>
        </tr>
    </thead>
    <tbody>

        @foreach ($model_data->reservation_offer as $key_rel => $value_rel)

            <tr role="row">
                <td>{{ $value_rel->id }}</td>
                <td>{{ $value_rel->team->name }}</td>
                <td>{{ $value_rel->status }}</td>
                <td>{{ Carbon\Carbon::parse($value_rel->created_at)->format('d.m.Y H:i') }}</td>
                <td style="width: 110px;">
                    @if(Request::segment(2) != 'delete')
                        <a href="javascript:void(0);" onclick="setReservationOffersAjaxData(this, '{{ $model_data->id }}', '{{ $value_rel->id }}', 'confirmed')" class="btn btn-sm btn-success btn-icon resofferbtn resofferbtn_wait wait_{{ $value_rel->id }}" title="{{ __('words.approve') }}" @if($model_data->status != 'open') style="display:none;" @endif role="button" data-toggle="tooltip">
                            <i class="fas fa-check"></i>
                        </a>
                    
                        <a href="javascript:void(0);" onclick="setReservationOffersAjaxData(this, '{{ $model_data->id }}', '{{ $value_rel->id }}', 'wait')" class="btn btn-sm btn-danger btn-icon resofferbtn resofferbtn_confirmed confirmed_{{ $value_rel->id }}" title="{{ __('words.approve_back') }}" @if($value_rel->status != 'confirmed') style="display:none;" @endif role="button" data-toggle="tooltip">
                            <i class="fas fa-times"></i>
                        </a>
                    @endif
                </td>
            </tr>

        @endforeach

    </tbody>
</table>
<!--end: Datatable-->

resources/views/tabs/user_photo.blade.php
<div class="form-group row">
	<label class="col-form-label col-lg-3 col-sm-12 text-lg-right"> {{ __('words.photograph') }} </label>
	<div class="col-lg-6 col-sm-12">
		<div class="card card-custom overlay" style="width: 200px; margin: auto;">
		    <div class="card-body p-0">
		        <div class="overlay-wrapper" id="imgUserPhoto">
		          <img src="{{ env('MEDIA_END').$model_data->image }}" alt="" class="rounded" style="width: 200px; height: auto;" />
		        </div>
		        <div class="overlay-layer align-items-start justify-content-end pt-5 pr-5">
		            <a href="{{ url('users/logo_delete/'.$model_data->id) }}" class="btn btn-clean btn-icon" title="{{ __('words.delete_photo') }}" ><i class="fas fa-trash-alt"></i></a>
		        </div>
		    </div>
		</div>
	</div>
	<div class="col-lg-3 col-sm-12">
		<div class="dropzone dropzone-default dropzone-primary" id="kt_dropzone_userphoto">
			<div class="dropzone-msg dz-message needsclick">
				<h3 class="dropzone-msg-title">{{ __('words.drag_and_drop_user_photo_here_or_click_to_upload') }}</h3>
				<span class="dropzone-msg-desc">{{ __('words.you_can_only_upload_1_file') }}</span>
			</div>
		</div>
	</div>
</div>